# Build
FROM node:26-slim AS builder
WORKDIR /app

COPY package.json package-lock.json ./
COPY server/package.json ./server/
RUN npm ci

COPY server ./server
WORKDIR /app/server

RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" npx prisma generate
RUN npm run build

# Production
FROM node:26-slim AS production

WORKDIR /app
COPY package.json package-lock.json ./
COPY server/package.json ./server/

RUN npm ci --omit=dev --no-audit --no-fund --workspace server && npm cache clean --force
COPY --from=builder /app/server/dist ./dist
COPY --from=builder /app/server/generated ./generated

EXPOSE 3000
CMD ["node", "dist/src/index.js"]
